let Places = ["Turkey", "Makkah", "Madinah", "Paris"];
console.log(Places);
console.log([...Places].sort());
console.log(Places);
console.log([...Places].reverse());
console.log(Places);
console.log(Places.reverse());
console.log(Places.reverse());
console.log(Places.sort());
console.log(Places.reverse());