var num4 = 10;
var num5 = 10;
console.log("Is num4 == num5 ? I predict true.");
console.log(num4 == num5);
var list1 = [1, 2, 3, 4, 5];
var list2 = [];
list1 = list2;
console.log("Is list1 == list2 ? I predict true.");
console.log(list1 == list2);
var array1 = ["Isha", "Muskaan", "Sabaa"];
var array2 = array1;
console.log("Is array1 == array2 ? I predict true.");
console.log(array1 == array2);
var array3 = ["Isha", "Muskaan", "Sabaa"];
var array4 = ["Isha", "Muskaan", "Sabaa"];
console.log("Is array1 == array2 ? I predict true.");
console.log(array1 == array2);
var num1 = 10;
var Name = "Isha";
console.log("Is typeof num1 == typeof Name ? I predict false.");
console.log(typeof num1 == typeof Name);
var list3 = [1, 2, 3, 4, 5];
var list4 = [0, 1, 2, 3, 4, 5];
console.log("Is list3.length == list4.length ? I predict false.");
console.log(list3.length == list4.length);
var str1 = ["Isha"];
var str2 = ["Isha"];
str2.push("Muskaan");
console.log("Is str1 == str2 ? I predict false.");
console.log(str1 == str2);
var str3 = ["Isha", "Muskaan"];
var str4 = ["Isha", "Muskaan"];
str3.pop;
console.log("Is str3 == str4 ? I predict false.");
console.log(str3 == str4);
//Error
var string = "100";
var num = 100;
console.log("Is string === num ? I predict false.");
console.log(string === num);
