var current_users = ["Isha", "Muskaan", "Sabaa", "Maryam", "Anum"];
var new_users = ["Ali", "Asad", "Zara", "Isha", "Anum"];
var n = 5;
console.log(n == 5);
console.log(n === 5);
console.log(n != 5);
console.log(n > 5);
console.log(n < 5);
console.log(n >= 5);
console.log(n <= 5);
